[2023-01-31T10:15:27.928+0000] {processor.py:153} INFO - Started process (PID=63) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:15:27.937+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:15:27.944+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:15:27.944+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:15:28.210+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:15:28.198+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:15:28.218+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:15:28.523+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:15:28.522+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:15:28.551+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:15:28.551+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:15:28.613+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.692 seconds
[2023-01-31T10:15:59.333+0000] {processor.py:153} INFO - Started process (PID=146) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:15:59.336+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:15:59.338+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:15:59.337+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:15:59.433+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:15:59.428+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:15:59.437+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:15:59.471+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:15:59.471+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:15:59.509+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:15:59.509+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:15:59.530+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.208 seconds
[2023-01-31T10:16:29.714+0000] {processor.py:153} INFO - Started process (PID=225) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:16:29.716+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:16:29.717+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:16:29.717+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:16:29.755+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:16:29.753+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:16:29.760+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:16:29.784+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:16:29.784+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:16:29.816+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:16:29.815+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:16:29.838+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.127 seconds
[2023-01-31T10:17:00.403+0000] {processor.py:153} INFO - Started process (PID=304) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:17:00.406+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:17:00.408+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:17:00.408+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:17:00.447+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:17:00.446+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:17:00.452+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:17:00.481+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:17:00.481+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:17:00.507+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:17:00.507+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:17:00.525+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.126 seconds
[2023-01-31T10:17:30.894+0000] {processor.py:153} INFO - Started process (PID=383) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:17:30.900+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:17:30.905+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:17:30.905+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:17:31.002+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:17:31.000+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:17:31.011+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:17:31.074+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:17:31.074+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:17:31.224+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:17:31.224+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:17:31.266+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.379 seconds
[2023-01-31T10:18:01.532+0000] {processor.py:153} INFO - Started process (PID=470) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:18:01.535+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:18:01.536+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:18:01.536+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:18:01.649+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:18:01.646+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:18:01.656+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:18:01.730+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:18:01.730+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:18:01.762+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:18:01.762+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:18:01.803+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.280 seconds
[2023-01-31T10:18:32.435+0000] {processor.py:153} INFO - Started process (PID=556) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:18:32.472+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:18:32.479+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:18:32.478+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:18:33.178+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:18:33.176+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:18:33.211+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:18:33.465+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:18:33.465+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:18:33.546+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:18:33.546+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:18:33.641+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 1.221 seconds
[2023-01-31T10:19:04.714+0000] {processor.py:153} INFO - Started process (PID=639) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:19:04.721+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:19:04.723+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:19:04.723+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:19:04.903+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:19:04.902+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:19:04.917+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:19:05.064+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:19:05.062+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:19:05.196+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:19:05.196+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:19:05.289+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.607 seconds
[2023-01-31T10:19:35.592+0000] {processor.py:153} INFO - Started process (PID=717) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:19:35.606+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:19:35.617+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:19:35.616+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:19:35.816+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:19:35.814+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:19:35.824+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:19:35.979+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:19:35.979+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:19:36.048+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:19:36.048+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:19:36.767+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 1.182 seconds
[2023-01-31T10:20:07.607+0000] {processor.py:153} INFO - Started process (PID=797) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:20:07.610+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:20:07.613+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:20:07.613+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:20:07.726+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:20:07.719+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:20:07.739+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:20:07.795+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:20:07.795+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:20:07.850+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:20:07.849+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:20:07.904+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.304 seconds
[2023-01-31T10:20:38.182+0000] {processor.py:153} INFO - Started process (PID=880) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:20:38.184+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:20:38.185+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:20:38.185+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:20:38.231+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:20:38.229+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:20:38.235+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:20:38.280+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:20:38.280+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:20:38.306+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:20:38.306+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:20:38.328+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.151 seconds
[2023-01-31T10:21:08.769+0000] {processor.py:153} INFO - Started process (PID=975) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:21:08.793+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:21:08.814+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:21:08.814+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:21:08.959+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:21:08.958+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:21:08.971+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:21:09.050+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:21:09.050+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:21:09.080+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:21:09.080+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:21:09.164+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.400 seconds
[2023-01-31T10:21:39.488+0000] {processor.py:153} INFO - Started process (PID=1044) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:21:39.494+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:21:39.508+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:21:39.508+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:21:39.564+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:21:39.562+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:21:39.569+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:21:39.607+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:21:39.606+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:21:39.630+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:21:39.630+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:21:39.686+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.203 seconds
[2023-01-31T10:22:10.069+0000] {processor.py:153} INFO - Started process (PID=1131) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:22:10.072+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:22:10.073+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:22:10.073+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:22:10.135+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:22:10.133+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:22:10.140+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:22:10.170+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:22:10.170+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:22:10.197+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:22:10.197+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:22:10.221+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.155 seconds
[2023-01-31T10:22:40.332+0000] {processor.py:153} INFO - Started process (PID=1210) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:22:40.334+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:22:40.334+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:22:40.334+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:22:40.378+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:22:40.376+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:22:40.384+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:22:40.413+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:22:40.413+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:22:40.430+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:22:40.430+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:22:40.442+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.113 seconds
[2023-01-31T10:23:11.100+0000] {processor.py:153} INFO - Started process (PID=1287) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:23:11.102+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:23:11.105+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:23:11.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:23:11.157+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:23:11.156+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:23:11.163+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:23:11.196+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:23:11.195+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:23:11.220+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:23:11.220+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:23:11.247+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.154 seconds
[2023-01-31T10:23:41.680+0000] {processor.py:153} INFO - Started process (PID=1366) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:23:41.681+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:23:41.682+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:23:41.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:23:41.716+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:23:41.714+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:23:41.720+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:23:41.743+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:23:41.743+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:23:41.760+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:23:41.760+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:23:41.771+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.093 seconds
[2023-01-31T10:24:12.140+0000] {processor.py:153} INFO - Started process (PID=1445) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:24:12.150+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:24:12.151+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:24:12.151+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:24:12.220+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:24:12.219+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:24:12.225+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:24:12.265+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:24:12.265+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:24:12.288+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:24:12.288+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:24:12.307+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.172 seconds
[2023-01-31T10:24:42.929+0000] {processor.py:153} INFO - Started process (PID=1523) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:24:42.931+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:24:42.933+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:24:42.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:24:42.966+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:24:42.963+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:24:42.971+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:24:43.002+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:24:43.001+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:24:43.035+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:24:43.035+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:24:43.055+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.129 seconds
[2023-01-31T10:25:13.900+0000] {processor.py:153} INFO - Started process (PID=1621) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:25:13.903+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:25:13.905+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:25:13.905+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:25:14.048+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:25:14.045+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:25:14.092+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:25:14.279+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:25:14.278+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:25:14.321+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:25:14.321+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:25:14.378+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.483 seconds
[2023-01-31T10:25:44.981+0000] {processor.py:153} INFO - Started process (PID=1701) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:25:44.983+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:25:44.989+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:25:44.989+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:25:45.066+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:25:45.065+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:25:45.071+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:25:45.097+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:25:45.096+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:25:45.146+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:25:45.146+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:25:45.178+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.201 seconds
[2023-01-31T10:26:16.939+0000] {processor.py:153} INFO - Started process (PID=1780) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:26:16.942+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:26:16.957+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:26:16.957+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:26:17.024+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:26:17.023+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:26:17.044+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:26:17.153+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:26:17.153+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:26:17.206+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:26:17.206+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:26:17.254+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.318 seconds
[2023-01-31T10:26:47.744+0000] {processor.py:153} INFO - Started process (PID=1863) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:26:47.745+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:26:47.746+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:26:47.746+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:26:47.791+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:26:47.787+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:26:47.798+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:26:47.834+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:26:47.834+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:26:47.856+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:26:47.855+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:26:47.885+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.145 seconds
[2023-01-31T10:27:18.444+0000] {processor.py:153} INFO - Started process (PID=1958) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:27:18.446+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:27:18.448+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:27:18.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:27:18.483+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:27:18.482+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:27:18.487+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:27:18.534+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:27:18.534+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:27:18.554+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:27:18.554+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:27:18.566+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.128 seconds
[2023-01-31T10:27:49.523+0000] {processor.py:153} INFO - Started process (PID=2038) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:27:49.525+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:27:49.526+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:27:49.526+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:27:49.565+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:27:49.563+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:27:49.569+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:27:49.594+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:27:49.594+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:27:49.611+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:27:49.611+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:27:49.625+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.105 seconds
[2023-01-31T10:28:20.662+0000] {processor.py:153} INFO - Started process (PID=2133) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:28:20.672+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:28:20.704+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:28:20.704+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:28:20.827+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:28:20.825+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:28:20.837+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:28:20.896+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:28:20.895+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:28:20.944+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:28:20.944+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:28:20.960+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.303 seconds
[2023-01-31T10:28:51.046+0000] {processor.py:153} INFO - Started process (PID=2212) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:28:51.048+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:28:51.049+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:28:51.049+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:28:51.096+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:28:51.095+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:28:51.101+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:28:51.145+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:28:51.144+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:28:51.180+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:28:51.180+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:28:51.217+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.173 seconds
[2023-01-31T10:29:21.924+0000] {processor.py:153} INFO - Started process (PID=2290) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:29:21.931+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:29:21.932+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:29:21.932+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:29:21.974+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:29:21.973+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:29:21.979+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:29:22.022+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:29:22.022+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:29:22.053+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:29:22.053+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:29:22.078+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.160 seconds
[2023-01-31T10:29:52.366+0000] {processor.py:153} INFO - Started process (PID=2369) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:29:52.368+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:29:52.370+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:29:52.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:29:52.420+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:29:52.419+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:29:52.424+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:29:52.451+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:29:52.451+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:29:52.488+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:29:52.488+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:29:52.512+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.152 seconds
[2023-01-31T10:30:23.406+0000] {processor.py:153} INFO - Started process (PID=2448) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:30:23.408+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:30:23.410+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:30:23.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:30:23.464+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:30:23.462+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:30:23.470+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:30:23.521+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:30:23.521+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:30:23.543+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:30:23.543+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:30:23.554+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.152 seconds
[2023-01-31T10:30:54.274+0000] {processor.py:153} INFO - Started process (PID=2527) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:30:54.276+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:30:54.278+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:30:54.278+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:30:54.317+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:30:54.316+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:30:54.321+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:30:54.346+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:30:54.345+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:30:54.377+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:30:54.377+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:30:54.408+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.137 seconds
[2023-01-31T10:31:25.190+0000] {processor.py:153} INFO - Started process (PID=2620) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:31:25.193+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:31:25.195+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:31:25.195+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:31:25.242+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:31:25.240+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:31:25.289+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:31:25.334+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:31:25.333+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:31:25.375+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:31:25.375+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:31:25.401+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.217 seconds
[2023-01-31T10:31:55.777+0000] {processor.py:153} INFO - Started process (PID=2698) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:31:55.779+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:31:55.782+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:31:55.782+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:31:55.839+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:31:55.838+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:31:55.844+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:31:55.869+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:31:55.869+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:31:55.885+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:31:55.885+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:31:55.911+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.138 seconds
[2023-01-31T10:32:26.964+0000] {processor.py:153} INFO - Started process (PID=2777) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:32:26.970+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:32:26.976+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:32:26.976+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:32:27.026+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:32:27.024+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:32:27.031+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:32:27.071+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:32:27.070+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:32:27.093+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:32:27.093+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:32:27.108+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.148 seconds
[2023-01-31T10:32:57.607+0000] {processor.py:153} INFO - Started process (PID=2872) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:32:57.611+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:32:57.614+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:32:57.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:32:57.676+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:32:57.675+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:32:57.692+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:32:57.718+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:32:57.718+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:32:57.759+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:32:57.758+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:32:57.770+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.167 seconds
[2023-01-31T10:33:28.803+0000] {processor.py:153} INFO - Started process (PID=2951) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:33:28.805+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:33:28.807+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:33:28.807+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:33:28.841+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:33:28.840+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:33:28.845+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:33:28.873+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:33:28.873+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:33:28.889+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:33:28.889+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:33:28.901+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.101 seconds
[2023-01-31T10:34:00.130+0000] {processor.py:153} INFO - Started process (PID=3046) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:34:00.134+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:34:00.136+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:34:00.136+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:34:00.182+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:34:00.181+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:34:00.188+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:34:00.251+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:34:00.250+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:34:00.329+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:34:00.329+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:34:00.430+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.306 seconds
[2023-01-31T10:34:31.240+0000] {processor.py:153} INFO - Started process (PID=3125) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:34:31.241+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:34:31.242+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:34:31.242+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:34:31.276+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:34:31.275+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:34:31.280+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:34:31.303+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:34:31.303+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:34:31.320+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:34:31.320+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:34:31.335+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.098 seconds
[2023-01-31T10:35:01.897+0000] {processor.py:153} INFO - Started process (PID=3212) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:35:01.911+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:35:01.913+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:35:01.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:35:01.990+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:35:01.984+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:35:01.998+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:35:02.033+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:35:02.033+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:35:02.085+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:35:02.085+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:35:02.122+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.230 seconds
[2023-01-31T10:35:33.082+0000] {processor.py:153} INFO - Started process (PID=3288) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:35:33.083+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:35:33.084+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:35:33.084+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:35:33.112+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:35:33.111+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:35:33.115+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:35:33.138+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:35:33.138+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:35:33.158+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:35:33.158+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:35:33.174+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.095 seconds
[2023-01-31T10:36:08.584+0000] {processor.py:153} INFO - Started process (PID=3383) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:36:08.588+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:36:08.593+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:36:08.593+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:36:08.742+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:36:08.714+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:36:08.755+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:36:08.791+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:36:08.791+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:36:08.872+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:36:08.872+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:36:08.924+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.345 seconds
[2023-01-31T10:36:40.646+0000] {processor.py:153} INFO - Started process (PID=3462) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:36:40.649+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:36:40.655+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:36:40.655+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:36:40.745+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:36:40.744+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:36:40.750+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:36:40.786+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:36:40.786+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:36:40.816+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:36:40.816+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:36:40.834+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.191 seconds
[2023-01-31T10:37:11.970+0000] {processor.py:153} INFO - Started process (PID=3545) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:37:11.975+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:37:11.978+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:37:11.978+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:37:12.639+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:37:12.634+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:37:12.665+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:37:12.744+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:37:12.744+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:37:12.793+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:37:12.793+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:37:12.827+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.862 seconds
[2023-01-31T10:37:43.814+0000] {processor.py:153} INFO - Started process (PID=3624) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:37:43.818+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:37:43.820+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:37:43.819+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:37:43.921+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:37:43.917+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:37:43.936+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:37:44.017+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:37:44.017+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:37:44.083+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:37:44.083+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:37:44.139+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.357 seconds
[2023-01-31T10:38:19.344+0000] {processor.py:153} INFO - Started process (PID=3713) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:38:19.347+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:38:19.348+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:38:19.348+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:38:19.432+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:38:19.429+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:38:19.441+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:38:19.489+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:38:19.489+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:38:19.520+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:38:19.520+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:38:19.562+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.221 seconds
[2023-01-31T10:38:49.641+0000] {processor.py:153} INFO - Started process (PID=3803) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:38:49.644+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:38:49.646+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:38:49.646+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:38:49.705+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:38:49.703+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:38:49.712+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:38:49.761+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:38:49.761+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:38:49.802+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:38:49.800+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:38:49.836+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.197 seconds
[2023-01-31T10:39:20.776+0000] {processor.py:153} INFO - Started process (PID=3881) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:39:20.787+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:39:20.789+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:39:20.789+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:39:20.862+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:39:20.861+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:39:20.868+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:39:20.898+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:39:20.898+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:39:20.920+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:39:20.920+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:39:20.952+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.179 seconds
[2023-01-31T10:39:51.748+0000] {processor.py:153} INFO - Started process (PID=3960) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:39:51.758+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:39:51.764+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:39:51.764+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:39:51.859+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:39:51.858+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:39:51.865+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:39:51.934+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:39:51.934+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:39:51.967+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:39:51.966+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:39:51.986+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.275 seconds
[2023-01-31T10:40:22.485+0000] {processor.py:153} INFO - Started process (PID=4039) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:40:22.486+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:40:22.488+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:40:22.488+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:40:22.527+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:40:22.526+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:40:22.531+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:40:22.564+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:40:22.564+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:40:22.590+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:40:22.590+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:40:22.611+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.129 seconds
[2023-01-31T10:40:53.445+0000] {processor.py:153} INFO - Started process (PID=4117) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:40:53.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:40:53.449+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:40:53.449+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:40:53.562+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:40:53.558+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:40:53.571+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:40:53.627+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:40:53.626+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:40:53.662+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:40:53.662+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:40:53.707+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.266 seconds
[2023-01-31T10:41:25.510+0000] {processor.py:153} INFO - Started process (PID=4196) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:41:25.513+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:41:25.517+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:41:25.517+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:41:25.589+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:41:25.586+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:41:25.607+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:41:25.662+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:41:25.662+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:41:25.685+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:41:25.685+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:41:25.752+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.246 seconds
[2023-01-31T10:41:58.151+0000] {processor.py:153} INFO - Started process (PID=4285) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:41:58.158+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:41:58.161+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:41:58.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:41:58.572+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:41:58.570+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:41:58.605+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:41:58.724+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:41:58.724+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:41:58.793+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:41:58.792+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:41:59.031+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.887 seconds
[2023-01-31T10:42:29.477+0000] {processor.py:153} INFO - Started process (PID=4372) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:42:29.481+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:42:29.485+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:42:29.485+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:42:29.551+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:42:29.550+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:42:29.559+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:42:29.602+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:42:29.602+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:42:29.646+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:42:29.646+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:42:29.718+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.248 seconds
[2023-01-31T10:42:59.828+0000] {processor.py:153} INFO - Started process (PID=4456) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:42:59.835+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:42:59.837+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:42:59.837+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:42:59.908+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:42:59.906+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:42:59.914+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:42:59.966+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:42:59.966+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:42:59.995+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:42:59.995+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:43:00.012+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.191 seconds
[2023-01-31T10:43:31.096+0000] {processor.py:153} INFO - Started process (PID=4534) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:43:31.113+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:43:31.128+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:43:31.128+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:43:32.376+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:43:32.280+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:43:32.414+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:43:32.520+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:43:32.519+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:43:32.589+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:43:32.588+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:43:32.625+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 1.947 seconds
[2023-01-31T10:44:03.004+0000] {processor.py:153} INFO - Started process (PID=4612) to work on /opt/airflow/dags/exercise17.py
[2023-01-31T10:44:03.011+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-01-31T10:44:03.013+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:44:03.013+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-01-31T10:44:03.116+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:44:03.115+0000] {abstractoperator.py:184} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 182, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-01-31T10:44:03.122+0000] {processor.py:753} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-01-31T10:44:03.196+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:44:03.195+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-01-31T10:44:03.250+0000] {logging_mixin.py:137} INFO - [2023-01-31T10:44:03.250+0000] {dag.py:3441} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-01-31T10:44:03.306+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/exercise17.py took 0.329 seconds
