[2023-01-24T17:55:02.550+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: easy.write_flights manual__2023-01-24T17:54:59.667589+00:00 [queued]>
[2023-01-24T17:55:02.559+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: easy.write_flights manual__2023-01-24T17:54:59.667589+00:00 [queued]>
[2023-01-24T17:55:02.560+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-24T17:55:02.560+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-24T17:55:02.561+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-24T17:55:02.572+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): write_flights> on 2023-01-24 17:54:59.667589+00:00
[2023-01-24T17:55:02.577+0000] {standard_task_runner.py:55} INFO - Started process 8310 to run task
[2023-01-24T17:55:02.583+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'easy', 'write_flights', 'manual__2023-01-24T17:54:59.667589+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/assignment_easy.py', '--cfg-path', '/tmp/tmpkuq37gqu']
[2023-01-24T17:55:02.585+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask write_flights
[2023-01-24T17:55:02.654+0000] {task_command.py:388} INFO - Running <TaskInstance: easy.write_flights manual__2023-01-24T17:54:59.667589+00:00 [running]> on host 2ee7bc173f76
[2023-01-24T17:55:02.744+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=easy
AIRFLOW_CTX_TASK_ID=write_flights
AIRFLOW_CTX_EXECUTION_DATE=2023-01-24T17:54:59.667589+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-24T17:54:59.667589+00:00
[2023-01-24T17:55:02.750+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment_easy.py", line 46, in write_flights
    json.dumps(data['flights'], f)
TypeError: dumps() takes 1 positional argument but 2 were given
[2023-01-24T17:55:02.764+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=easy, task_id=write_flights, execution_date=20230124T175459, start_date=20230124T175502, end_date=20230124T175502
[2023-01-24T17:55:02.777+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task write_flights (dumps() takes 1 positional argument but 2 were given; 8310)
[2023-01-24T17:55:02.799+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-24T17:55:02.822+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
