[2023-01-24T17:15:40.588+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: maingoal.write_flights manual__2023-01-24T17:15:39.438535+00:00 [queued]>
[2023-01-24T17:15:40.594+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: maingoal.write_flights manual__2023-01-24T17:15:39.438535+00:00 [queued]>
[2023-01-24T17:15:40.595+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-24T17:15:40.596+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-24T17:15:40.596+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-24T17:15:40.606+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): write_flights> on 2023-01-24 17:15:39.438535+00:00
[2023-01-24T17:15:40.611+0000] {standard_task_runner.py:55} INFO - Started process 4951 to run task
[2023-01-24T17:15:40.615+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'maingoal', 'write_flights', 'manual__2023-01-24T17:15:39.438535+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/exam1.py', '--cfg-path', '/tmp/tmp8zc5kjd8']
[2023-01-24T17:15:40.615+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask write_flights
[2023-01-24T17:15:40.669+0000] {task_command.py:388} INFO - Running <TaskInstance: maingoal.write_flights manual__2023-01-24T17:15:39.438535+00:00 [running]> on host 2ee7bc173f76
[2023-01-24T17:15:40.720+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=maingoal
AIRFLOW_CTX_TASK_ID=write_flights
AIRFLOW_CTX_EXECUTION_DATE=2023-01-24T17:15:39.438535+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-24T17:15:39.438535+00:00
[2023-01-24T17:15:40.725+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/exam1.py", line 49, in write_flights
    f.write(json.dumps(flights))
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PlainXComArg is not JSON serializable
[2023-01-24T17:15:40.735+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=maingoal, task_id=write_flights, execution_date=20230124T171539, start_date=20230124T171540, end_date=20230124T171540
[2023-01-24T17:15:40.743+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 18 for task write_flights (Object of type PlainXComArg is not JSON serializable; 4951)
[2023-01-24T17:15:40.796+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-24T17:15:40.813+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
